export const types = {
  //Sync
  FILL_USERS: 'FILL_USERS',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  SET_EDITING_USER_ID: 'SET_EDITING_USER_ID',
  CLEAR_EDITING_USER_ID: 'CLEAR_EDITING_USER_ID',
  
  //Async
  FETCH_USERS: 'FETCH_USERS',
  CREATE_USER_ASYNC: 'CREATE_USER_ASYNC',
  UPDATE_USER_ASYNC: 'UPDATE_USER_ASYNC',
  DELETE_USER_ASYNC: 'DELETE_USER_ASYNC',
}